import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#FBF2ED',
    },
    display: {
        flex: 1,
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        padding: 16,
        width: '100%',
    },
    displayTextContainer: {
        alignItems: 'flex-end',
        width: '100%',
        justifyContent: 'flex-end',
    },
    displayLandscape: {
        paddingBottom: 8,
        paddingTop: 0,
        justifyContent: 'flex-end',
        width: '100%',  
    },
    expression: {
        fontSize: 32,
        color: '#B7BCBF',
        textAlign: 'right',
        marginBottom: 8,
        width: '100%',
    },
    result: {
        fontSize: 48,
        color: '#B7BCBF',
        textAlign: 'right',
        width: '100%',
    },
    appBarContainer: {
        width: '100%',
        backgroundColor: '#CDD5C6',
    },
    appBar:{
        width: '100%',
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 4,
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: 10,
        backgroundColor: '#CDD5C6',
    },
    titleAppBar: {
        color: '#64786F',
        fontSize: 24,
        fontWeight: 'bold',
    },
    buttonsSection: {
        width: '100%',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    buttonContainer: {
        width: '80%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: 20,
        marginBottom: 20,
    },
    buttonWrapper:{
        width: '22%',
        height: 70,
        aspectRatio: 1,
        marginVertical: 8,
        borderRadius: 35,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#CDD5C6',
    },
    buttonText: {
        fontSize: 28,
        color: '#64786F',
        fontStyle: '',
    },
});